FROM mcr.microsoft.com/windows/servercore:ltsc2019

COPY ./estafette-extension-envvars.exe C:/estafette-extension-envvars.exe

ENV ESTAFETTE_LOG_FORMAT="console"

USER ContainerAdministrator

ENTRYPOINT ["C:/estafette-extension-envvars.exe"]